/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ColorPicker: typeof import('./components/ColorPicker.vue')['default']
    ContextMenu: typeof import('./components/ContextMenu.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Graphics: typeof import('./components/Graphics.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    ListEquip: typeof import('./components/ListEquip.vue')['default']
    Preview: typeof import('./components/Preview.vue')['default']
    Props: typeof import('./components/props/Props.vue')['default']
    PropsEquip: typeof import('./components/props/PropsEquip.vue')['default']
    PropsEquipAutoCreatePoints: typeof import('./components/props/PropsEquipAutoCreatePoints.vue')['default']
    PropsFile: typeof import('./components/props/PropsFile.vue')['default']
    PropsPen: typeof import('./components/props/PropsPen.vue')['default']
    PropsPoint: typeof import('./components/props/PropsPoint.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    Toolbar: typeof import('./components/toolbar/Toolbar.vue')['default']
    ToolbarAnchor: typeof import('./components/toolbar/ToolbarAnchor.vue')['default']
    ToolbarDrawLine: typeof import('./components/toolbar/ToolbarDrawLine.vue')['default']
    ToolbarFile: typeof import('./components/toolbar/ToolbarFile.vue')['default']
    ToolbarFocus: typeof import('./components/toolbar/ToolbarFocus.vue')['default']
    ToolbarFromArrow: typeof import('./components/toolbar/ToolbarFromArrow.vue')['default']
    ToolbarLayout: typeof import('./components/toolbar/ToolbarLayout.vue')['default']
    ToolbarLine: typeof import('./components/toolbar/ToolbarLine.vue')['default']
    ToolbarLineType: typeof import('./components/toolbar/ToolbarLineType.vue')['default']
    ToolbarMagnifier: typeof import('./components/toolbar/ToolbarMagnifier.vue')['default']
    ToolbarMiniMap: typeof import('./components/toolbar/ToolbarMiniMap.vue')['default']
    ToolbarPen: typeof import('./components/toolbar/ToolbarPen.vue')['default']
    ToolbarPencil: typeof import('./components/toolbar/ToolbarPencil.vue')['default']
    ToolbarPreview: typeof import('./components/toolbar/ToolbarPreview.vue')['default']
    ToolbarRedo: typeof import('./components/toolbar/ToolbarRedo.vue')['default']
    ToolbarScaleDefault: typeof import('./components/toolbar/ToolbarScaleDefault.vue')['default']
    ToolbarText: typeof import('./components/toolbar/ToolbarText.vue')['default']
    ToolbarToArrow: typeof import('./components/toolbar/ToolbarToArrow.vue')['default']
    ToolbarTopView: typeof import('./components/toolbar/ToolbarTopView.vue')['default']
    ToolbarUndo: typeof import('./components/toolbar/ToolbarUndo.vue')['default']
    UserComponents: typeof import('./components/UserComponents.vue')['default']
    View: typeof import('./components/View.vue')['default']
  }
}
