/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    Footer: typeof import('./components/Footer.vue')['default']
    Graphics: typeof import('./components/Graphics.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IconItem: typeof import('./components/IconItem.vue')['default']
    Meta2dHeader: typeof import('./components/Meta2dHeader.vue')['default']
    Meta2dView: typeof import('./components/Meta2dView.vue')['default']
    Preview: typeof import('./components/Preview.vue')['default']
    Props: typeof import('./components/props/Props.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./components/toolbar/Toolbar.vue')['default']
    ToolbarItem: typeof import('./components/toolbar/ToolbarItem.vue')['default']
    ToolbarText: typeof import('./components/toolbar/ToolbarText.vue')['default']
    View: typeof import('./components/View.vue')['default']
  }
}
